---
- name: Detect OS and run specific tasks
  hosts: all
  become: yes
  gather_facts: yes

  tasks:
    - name: CentOS and Rocky task
	  shell: |
	    cd /home
        yum -y install wget
        wget https://www.rconfig.com/downloads/rconfig6_centos8.sh -O /home/install.sh
        chmod +x install.sh
        ./install.sh
      when: ansible_facts['distribution'] in ['CentOS', 'Rocky']
      debug:
        msg: "This task is for CentOS and Rocky."

    - name: RHEL 8 task
      shell: |
	    cd /home
        yum -y install wget
        wget https://www.rconfig.com/downloads/rconfig6_rhel8.sh -O /home/install.sh
        chmod +x install.sh
        ./install.sh  
      when: ansible_facts['distribution'] == 'RedHat' and ansible_facts['distribution_major_version'] == '8'
      debug:
        msg: "This task is for RHEL 8."

    - name: RHEL 7 task
	    shell: |
	      cd /home
          yum -y install wget
          wget https://www.rconfig.com/downloads/rconfig6_rhel8.sh -O /home/install.sh
          chmod +x install.sh
          ./install.sh
      when: ansible_facts['distribution'] == 'RedHat' and ansible_facts['distribution_major_version'] == '7'
      debug:
        msg: "This task is for RHEL 7."

    - name: Ubuntu 18.04 and above task
	  shell: |
	    cd ~/
        sudo apt -y install wget
        wget https://www.rconfig.com/downloads/rconfig6_ubuntu.sh -O install.sh
        chmod +x install.sh
        sudo ./install.sh
      when: ansible_facts['distribution'] == 'Ubuntu' and ansible_facts['distribution_version'] | version_compare('18.04', '>=')
      debug:
        msg: "This task is for Ubuntu 18.04 and above."
